#!/usr/bin/env bash
# Script to install nginx server listening on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
