#!/usr/bin/env bash
# Display numbers from 1 to 100 in list format.
#  Displays "FizzBuzz" when the number is a multiple of 3 and 5
# Display "Fizz" when the number is a multiple of 3.
# Display "Buzz" when the number is a multiple of 5
# other, display the number.

for number in {1..100}
do
    if (( number % 3 == 0 && number % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( number % 3 == 0 ))
    then
        echo "Fizz"
    elif (( number % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$number"
    fi
done